### ISSUE TITLE
请问flink 1.12.2能不能完成上面的步骤

### ISSUE THREAD

**Issue by hzuzhangbaoqi** [langlibaixia/FlinkCDC-Hudi#2]
请问flink 1.12.2能不能完成上面的步骤

**Comment by langlibaixia** [comment]
您好，可以完成上面步骤，但是存在性能和效率等方面的问题，flink1.12.*支持cdc版本为1.2和1.3，hudi0.9的版本是支持的，0.9以上需要验证下，hudi的包需要自己编译。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月3日(周六) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [langlibaixia/FlinkCDC-Hudi] 请问flink 1.12.2能不能完成上面的步骤 (Issue #2)




 
请问flink 1.12.2能不能完成上面的步骤

**Comment by langlibaixia** [comment]
您好，可以完成上述操作，但是存在效率和性能等方面的问题，flink1.12.*支持的cdc版本为1.2和1.3，支持的hudi版本为0.9，需要自行编译一下hudi包。可以考虑升级flink cdc链路到稳定的版本，另外可以加官方钉钉群交流。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月3日(周六) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [langlibaixia/FlinkCDC-Hudi] 请问flink 1.12.2能不能完成上面的步骤 (Issue #2)




 
请问flink 1.12.2能不能完成上面的步骤

**Comment by hzuzhangbaoqi** [comment]
![Snipaste_2022-09-03_12-03-39](https://user-images.githubusercontent.com/29708650/188263793-01889bc8-bd3b-4640-bcd2-5294a6b1a313.png)

请问这个问题是jar引用不对引起的吗？

**Comment by hzuzhangbaoqi** [comment]
Caused by: java.io.InvalidClassException: org.apache.hudi.sink.compact.CompactionPlanOperator; local class incompatible: stream classdesc serialVersionUID = 7111548745766441276, local class serialVersionUID = -6306705165553718287
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:742) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2145) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1976) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2309) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1793) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2557) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2478) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2336) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1793) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:558) ~[?:1.8.0_302]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:516) ~[?:1.8.0_302]
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:615) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:600) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:587) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:541) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:317) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
	... 6 more
2022-09-03 17:59:00,480 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Call stack:
    at java.lang.Thread.getStackTrace(Thread.java:1559)
    at org.apache.flink.runtime.taskmanager.Task.transitionState(Task.java:1041)
    at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:828)
    at org.apache.flink.runtime.taskmanager.Task.run(Task.java:571)
    at java.lang.Thread.run(Thread.java:748)

2022-09-03 17:59:00,480 WARN  org.apache.flink.configuration.Configuration                 [] - Config uses deprecated configuration key 'state.backend.fs.checkpointdir' instead of proper key 'state.checkpoints.dir'
2022-09-03 17:59:00,481 INFO  org.apache.flink.streaming.runtime.tasks.StreamTask          [] - No state backend has been configured, using default (Memory / JobManager) MemoryStateBackend (data in heap memory / checkpoints to JobManager) (checkpoints: 'hdfs:/flink/checkpoints', savepoints: 'hdfs:/flink/checkpoints', asynchronous: TRUE, maxStateSize: 5242880)
2022-09-03 17:59:00,481 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Join(joinType=[LeftOuterJoin], where=[(product_id = id)], select=[order_id, order_date, customer_name, price, product_id, order_status, id, name, description], leftInputSpec=[HasUniqueKey], rightInputSpec=[JoinKeyContainsUniqueKey]) -> Calc(select=[order_id, order_date, customer_name, price, product_id, order_status, name, description]) (1/1)#0 (b31bbb8c8a0c28d66fba004b0281a01b) switched from DEPLOYING to RUNNING.
2022-09-03 17:59:00,481 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Freeing task resources for compact_plan_generate (1/1)#0 (6f51b6133cc0b0a1fc9a7ea414bbe9fd).

**Comment by hzuzhangbaoqi** [comment]
插入sql的过程中报错应该如何解决？

**Comment by hzuzhangbaoqi** [comment]
./sql-client.sh embedded -j /opt/client/Flink/flink/lib/hudi-flink-bundle_2.12-0.9.0.jar -j /opt/client/Flink/flink/lib/flink-sql-connector-mysql-cdc-1.2.0.jar -j /opt/client/Flink/flink/lib/flink-connector-kafka_2.12-1.12.2.jar -j /opt/client/Flink/flink/lib/kafka-clients-2.4.0-hw-ei-312032.jar shell

**Comment by hzuzhangbaoqi** [comment]
这个是提交命令

**Comment by langlibaixia** [comment]
应该是flink 服务端和客户端版本不一致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月3日(周六) 晚上6:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [langlibaixia/FlinkCDC-Hudi] 请问flink 1.12.2能不能完成上面的步骤 (Issue #2)




 
Caused by: java.io.InvalidClassException: org.apache.hudi.sink.compact.CompactionPlanOperator; local class incompatible: stream classdesc serialVersionUID = 7111548745766441276, local class serialVersionUID = -6306705165553718287
 at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:742) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2145) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1976) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2309) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1793) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2557) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2478) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2336) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1793) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:558) ~[?:1.8.0_302]
 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:516) ~[?:1.8.0_302]
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:615) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:600) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:587) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
 at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:541) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
 at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:317) ~[flink-dist_2.11-1.12.2-hw-ei-312032.jar:1.12.2-hw-ei-312032]
 ... 6 more
 2022-09-03 17:59:00,480 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Call stack:
 at java.lang.Thread.getStackTrace(Thread.java:1559)
 at org.apache.flink.runtime.taskmanager.Task.transitionState(Task.java:1041)
 at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:828)
 at org.apache.flink.runtime.taskmanager.Task.run(Task.java:571)
 at java.lang.Thread.run(Thread.java:748)
 
2022-09-03 17:59:00,480 WARN  org.apache.flink.configuration.Configuration                 [] - Config uses deprecated configuration key 'state.backend.fs.checkpointdir' instead of proper key 'state.checkpoints.dir'
 2022-09-03 17:59:00,481 INFO  org.apache.flink.streaming.runtime.tasks.StreamTask          [] - No state backend has been configured, using default (Memory / JobManager) MemoryStateBackend (data in heap memory / checkpoints to JobManager) (checkpoints: 'hdfs:/flink/checkpoints', savepoints: 'hdfs:/flink/checkpoints', asynchronous: TRUE, maxStateSize: 5242880)
 2022-09-03 17:59:00,481 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Join(joinType=[LeftOuterJoin], where=[(product_id = id)], select=[order_id, order_date, customer_name, price, product_id, order_status, id, name, description], leftInputSpec=[HasUniqueKey], rightInputSpec=[JoinKeyContainsUniqueKey]) -&gt; Calc(select=[order_id, order_date, customer_name, price, product_id, order_status, name, description]) (1/1)#0 (b31bbb8c8a0c28d66fba004b0281a01b) switched from DEPLOYING to RUNNING.
 2022-09-03 17:59:00,481 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Freeing task resources for compact_plan_generate (1/1)#0 (6f51b6133cc0b0a1fc9a7ea414bbe9fd).
